artifacts_root: artifacts

crawl_data:
  root_dir: data
  data_path: data/data.csv

data_process:
  root_dir: artifacts/data_process
  train_path: artifacts/data_process/train.csv
  test_path: artifacts/data_process/test.csv
  data_path: data/data.csv

model_train:
  root_dir: artifacts/model_train
  model_path: artifacts/model_train/model.pkl
  vectorizer_path: artifacts/model_train/vectorizer.pkl
  train_data_path: artifacts/data_process/train.csv
  test_data_path: artifacts/data_process/test.csv